version: '3'
services:
  weather:
    build: weather/.
  time:
    build: debugTime/.
  gateway:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro